import type { ModuleRequirement } from "@tomflow/proflow-module-contract";

import type { ResolvedModule } from "../contracts.ts";
import type { WorkspacePaths } from "../paths.ts";
import { writeInstallDoc } from "../persistence/index.ts";
import { resolveModuleConfig } from "../preflight/index.ts";
import { redactDeep, redactSecretValues } from "../security/index.ts";

export interface InstallDocInput {
	modules: readonly ResolvedModule[];
	config?: Record<string, Record<string, string>>;
	now?: Date;
}

export interface GenerateInstallDocInput extends InstallDocInput {
	paths: WorkspacePaths;
}

function compareRef(a: string, b: string): number {
	return a < b ? -1 : a > b ? 1 : 0;
}

function requirementLine(
	moduleRef: string,
	requirement: ModuleRequirement,
): string {
	switch (requirement.kind) {
		case "runtime":
			return `- \`${moduleRef}\`: runtime \`${requirement.runtime}\` ${requirement.versionRange}`;
		case "executable":
			return `- \`${moduleRef}\`: executable \`${requirement.command}\`${
				requirement.versionRange !== undefined
					? ` ${requirement.versionRange}`
					: ""
			}`;
		case "filesystem":
			return `- \`${moduleRef}\`: filesystem \`${requirement.path}\` (${requirement.access})`;
		case "port":
			return `- \`${moduleRef}\`: port ${requirement.port}/${requirement.protocol}`;
		case "network":
			return `- \`${moduleRef}\`: network \`${requirement.url}\``;
		case "module-contract":
			return `- \`${moduleRef}\`: module-contract \`${requirement.contractRef}\` ${requirement.versionRange}`;
		case "human":
			return `- \`${moduleRef}\`: human — ${requirement.action}`;
	}
}

function collectRawSecrets(
	modules: readonly ResolvedModule[],
	config: Record<string, Record<string, string>> | undefined,
): string[] {
	const secrets: string[] = [];
	for (const module of modules) {
		const resolved = resolveModuleConfig(module, config?.[module.moduleRef]);
		const sensitiveKeys = new Set(
			module.configSlots
				.filter((slot) => slot.sensitive === true && slot.type !== "secretRef")
				.map((slot) => slot.key),
		);
		for (const [key, value] of Object.entries(resolved.values)) {
			if (sensitiveKeys.has(key) && value.length > 0) secrets.push(value);
		}
	}
	return secrets;
}

/**
 * Renders the generated INSTALL document from the real selected module set:
 * module refs/versions, machine/runtime requirements, secret-redacted config
 * slots, external resources, effects, human actions, and the verification plan.
 * No raw secret value may survive — config values are redacted by key, and the
 * whole document is deep-redacted against every known raw secret value.
 */
export function renderInstallDoc(input: InstallDocInput): string {
	const generatedAt = (input.now ?? new Date()).toISOString();
	const modules = [...input.modules].sort((a, b) =>
		compareRef(a.moduleRef, b.moduleRef),
	);

	const lines: string[] = [];
	lines.push("# ProFlow Deployment — Generated INSTALL");
	lines.push("");
	lines.push(
		`> Generated at ${generatedAt}. Regenerated by \`platform manifest\`.`,
	);
	lines.push("");

	lines.push("## Selected Module Set");
	lines.push("");
	for (const module of modules) {
		lines.push(
			`- \`${module.moduleRef}\` (\`${module.packageName}@${module.moduleVersion}\`, kind: \`${module.kind}\`)`,
		);
	}
	lines.push("");

	lines.push("## Requirements");
	lines.push("");
	for (const module of modules) {
		for (const requirement of module.requirements) {
			lines.push(requirementLine(module.moduleRef, requirement));
		}
	}
	lines.push("");

	lines.push("## Config Slots");
	lines.push("");
	for (const module of modules) {
		const resolved = resolveModuleConfig(
			module,
			input.config?.[module.moduleRef],
		);
		const values = redactSecretValues(resolved.values, resolved.secretRefs);
		for (const slot of module.configSlots) {
			const value = values[slot.key];
			const suffix = value !== undefined ? ` = \`${value}\`` : "";
			const required = slot.required ? " (required)" : "";
			lines.push(
				`- \`${module.moduleRef}\`.\`${slot.key}\` [${slot.type}]${required}${suffix}`,
			);
		}
	}
	lines.push("");

	const external = modules.filter(
		(module) => module.kind === "external-resource",
	);
	if (external.length > 0) {
		lines.push("## External Resources");
		lines.push("");
		for (const module of external) {
			lines.push(
				`- \`${module.moduleRef}\` (\`${module.packageName}@${module.moduleVersion}\`)`,
			);
		}
		lines.push("");
	}

	lines.push("## Effects");
	lines.push("");
	for (const module of modules) {
		for (const effect of module.effects) {
			lines.push(
				`- \`${module.moduleRef}\`: [${effect.kind}] ${effect.description}`,
			);
		}
	}
	lines.push("");

	const humanActions = modules.flatMap((module) =>
		module.requirements
			.filter((requirement) => requirement.kind === "human")
			.map((requirement) => ({
				moduleRef: module.moduleRef,
				action: requirement.action,
			})),
	);
	if (humanActions.length > 0) {
		lines.push("## Human Actions");
		lines.push("");
		for (const action of humanActions) {
			lines.push(`- \`${action.moduleRef}\`: ${action.action}`);
		}
		lines.push("");
	}

	const missingRequiredConfig: Record<string, Record<string, string>> = {};
	for (const module of modules) {
		const resolved = resolveModuleConfig(
			module,
			input.config?.[module.moduleRef],
		);
		for (const slot of module.configSlots) {
			if (!slot.required || resolved.values[slot.key] !== undefined) continue;
			const placeholder =
				slot.type === "secretRef"
					? "secret://provider/name"
					: slot.type === "url"
						? "https://example.invalid"
						: slot.type === "path"
							? "/absolute/path"
							: slot.type === "moduleRef"
								? "module-ref"
								: "<value>";
			const moduleConfig = missingRequiredConfig[module.moduleRef] ?? {};
			moduleConfig[slot.key] = placeholder;
			missingRequiredConfig[module.moduleRef] = moduleConfig;
		}
	}

	lines.push("## Configure Before Start");
	lines.push("");
	if (Object.keys(missingRequiredConfig).length === 0) {
		lines.push(
			"No required configuration is currently missing. Re-run `platform preflight --intent start` before starting to confirm current runtime readiness.",
		);
	} else {
		lines.push(
			"Create a JSON config file (for example `./proflow-config.json`) using the required missing slots below. Replace placeholders with real environment-specific values. `secretRef` values must remain opaque references such as `secret://provider/name`; do not place raw secrets in this file.",
		);
		lines.push("");
		lines.push("```json");
		lines.push(JSON.stringify({ modules: missingRequiredConfig }, null, 2));
		lines.push("```");
		lines.push("");
		lines.push("Apply and re-check the configuration:");
		lines.push("");
		lines.push(
			"1. `platform plan --intent configure --config ./proflow-config.json`",
		);
		lines.push("2. Copy the returned `planRef`.");
		lines.push("3. `platform apply <planRef>`");
		lines.push("4. `platform preflight --intent start`");
		lines.push(
			"5. Resolve any remaining human or external-resource actions reported by preflight, then run the same preflight command again until the Platform reports the expected readiness state.",
		);
	}
	lines.push("");

	lines.push("## Verification Plan");
	lines.push("");
	for (const module of modules) {
		for (const verificationCheck of module.verification.checks) {
			lines.push(
				`- \`${module.moduleRef}\`: \`${verificationCheck.id}\` (${verificationCheck.lifecycle}) — ${verificationCheck.description}`,
			);
		}
	}

	const content = `${lines.join("\n")}\n`;

	// defense-in-depth: deep-redact every raw secret value wherever it appears
	const rawSecrets = collectRawSecrets(modules, input.config);
	const redacted = redactDeep(content, rawSecrets);
	return typeof redacted === "string" ? redacted : content;
}

export async function generateInstallDoc(
	input: GenerateInstallDocInput,
): Promise<string> {
	const content = renderInstallDoc(input);
	await writeInstallDoc(input.paths, content);
	return content;
}
